TWEAK_NAME = AutoAlerts

$(TWEAK_NAME)_FILES = Tweak.x AAConfigurationViewController.x AAAppIconCell.m ../Model/AAAlertInfo.m AAUserDefaultsStore.m AAAlertManager.m
$(TWEAK_NAME)_LIBRARIES = sandy

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
