TWEAK_NAME = AutoAlerts

$(TWEAK_NAME)_FILES = Tweak.x AAConfigurationViewController.x AAAppIconCell.m ../Model/AAAlertInfo.m AACoreDataStack.m AAAlertManager.m
$(TWEAK_NAME)_FRAMEWORKS = CoreData

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
