BUNDLE_NAME = AutoAlertsPreferences

$(BUNDLE_NAME)_FILES = AARootListController.x ../Model/AAAlertInfo.m ../Tweak/AAAlertManager.m ../Tweak/AAUserDefaultsStore.m AAApp.m AAAppOverviewController.x AAAlertOverviewController.x
$(BUNDLE_NAME)_CFLAGS = -fobjc-arc -w
$(BUNDLE_NAME)_FRAMEWORKS = UIKit
$(BUNDLE_NAME)_PRIVATE_FRAMEWORKS = Preferences
$(BUNDLE_NAME)_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
